version: "3.9"
services:
  carpool-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "9091:9091"
    networks:
      - peakpal-network
    environment:
      - DB_SOURCE=postgresql://root:secret@peakpal_db_container:5432/peakpal_carpool_db?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    entrypoint:
      [
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
volumes:
  data-volume:
networks:
  peakpal-network:
    name: peakpal-network
    external: true