// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Carpool struct {
	ID           int64            `json:"id"`
	ContactInfo  string           `json:"contact_info"`
	DriverID     int64            `json:"driver_id"`
	MaxPassenger int32            `json:"max_passenger"`
	Price        int32            `json:"price"`
	AblePickUp   bool             `json:"able_pick_up"`
	ResortID     int64            `json:"resort_id"`
	DepartureAt  pgtype.Timestamp `json:"departure_at"`
	// provider write
	AcceptPaymentType string           `json:"accept_payment_type"`
	Currency          string           `json:"currency"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type CarpoolRequest struct {
	ID              int64            `json:"id"`
	CarpoolID       int64            `json:"carpool_id"`
	PassengerID     int64            `json:"passenger_id"`
	BoardingStation int64            `json:"boarding_station"`
	PaymentType     string           `json:"payment_type"`
	Currency        string           `json:"currency"`
	ContactInfo     string           `json:"contact_info"`
	Approved        bool             `json:"approved"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type CarpoolUser struct {
	ID          int64            `json:"id"`
	PassengerID int64            `json:"passenger_id"`
	CarpoolID   int64            `json:"carpool_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Station struct {
	ID          int64  `json:"id"`
	CarpoolID   int64  `json:"carpool_id"`
	StationName string `json:"station_name"`
	// How long it take from first station
	ArrivalMinutes int32            `json:"arrival_minutes"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}
