// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"context"
)

type Querier interface {
	CreateCarpool(ctx context.Context, arg CreateCarpoolParams) (Carpool, error)
}

var _ Querier = (*Queries)(nil)
