// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: stations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStation = `-- name: CreateStation :one
INSERT INTO stations (
    trip_id,
    station_name,
    arrival_minutes
)VALUES(
    $1,$2,$3
)RETURNING id, trip_id, station_name, arrival_minutes, created_at
`

type CreateStationParams struct {
	TripID         int64  `json:"trip_id"`
	StationName    string `json:"station_name"`
	ArrivalMinutes int32  `json:"arrival_minutes"`
}

func (q *Queries) CreateStation(ctx context.Context, arg CreateStationParams) (Station, error) {
	row := q.db.QueryRow(ctx, createStation, arg.TripID, arg.StationName, arg.ArrivalMinutes)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.StationName,
		&i.ArrivalMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStation = `-- name: DeleteStation :exec
DELETE FROM stations
WHERE id = $1
`

func (q *Queries) DeleteStation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStation, id)
	return err
}

const getStation = `-- name: GetStation :one
SELECT 
    s.id AS station_id,
    s.station_name,
    s.arrival_minutes,
    t.driver_id,
    p.passenger_id
FROM
    stations s
LEFT JOIN trips t ON s.tip_id = t.id
LEFT JOIN trip_applications p ON s.tip_id = p.tip_id
WHERE
    s.id = $1
`

type GetStationRow struct {
	StationID      int64       `json:"station_id"`
	StationName    string      `json:"station_name"`
	ArrivalMinutes int32       `json:"arrival_minutes"`
	DriverID       pgtype.Int8 `json:"driver_id"`
	PassengerID    pgtype.Int8 `json:"passenger_id"`
}

func (q *Queries) GetStation(ctx context.Context, id int64) (GetStationRow, error) {
	row := q.db.QueryRow(ctx, getStation, id)
	var i GetStationRow
	err := row.Scan(
		&i.StationID,
		&i.StationName,
		&i.ArrivalMinutes,
		&i.DriverID,
		&i.PassengerID,
	)
	return i, err
}

const listStations = `-- name: ListStations :many
SELECT id, trip_id, station_name, arrival_minutes, created_at FROM stations
WHERE trip_id = $1
ORDER BY arrival_minutes
`

func (q *Queries) ListStations(ctx context.Context, tripID int64) ([]Station, error) {
	rows, err := q.db.Query(ctx, listStations, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Station{}
	for rows.Next() {
		var i Station
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.StationName,
			&i.ArrivalMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
