// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: trip_requests.sql

package db

import (
	"context"
)

const createTripApplication = `-- name: CreateTripApplication :one
INSERT INTO trip_applications (
    trip_id,
    passenger_id,
    boarding_station,
    payment_type,
    currency,
    contact_info
)VALUES(
    $1,$2,$3,$4,$5,$6
)RETURNING id, trip_id, passenger_id, boarding_station, payment_type, currency, contact_info, approved, created_at
`

type CreateTripApplicationParams struct {
	TripID          int64  `json:"trip_id"`
	PassengerID     int64  `json:"passenger_id"`
	BoardingStation int64  `json:"boarding_station"`
	PaymentType     string `json:"payment_type"`
	Currency        string `json:"currency"`
	ContactInfo     string `json:"contact_info"`
}

func (q *Queries) CreateTripApplication(ctx context.Context, arg CreateTripApplicationParams) (TripApplication, error) {
	row := q.db.QueryRow(ctx, createTripApplication,
		arg.TripID,
		arg.PassengerID,
		arg.BoardingStation,
		arg.PaymentType,
		arg.Currency,
		arg.ContactInfo,
	)
	var i TripApplication
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.PassengerID,
		&i.BoardingStation,
		&i.PaymentType,
		&i.Currency,
		&i.ContactInfo,
		&i.Approved,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTripApplication = `-- name: DeleteTripApplication :exec
DELETE FROM trip_applications
WHERE id = $1
`

func (q *Queries) DeleteTripApplication(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTripApplication, id)
	return err
}

const getTripApplication = `-- name: GetTripApplication :one
SELECT id, trip_id, passenger_id, boarding_station, payment_type, currency, contact_info, approved, created_at FROM trip_applications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTripApplication(ctx context.Context, id int64) (TripApplication, error) {
	row := q.db.QueryRow(ctx, getTripApplication, id)
	var i TripApplication
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.PassengerID,
		&i.BoardingStation,
		&i.PaymentType,
		&i.Currency,
		&i.ContactInfo,
		&i.Approved,
		&i.CreatedAt,
	)
	return i, err
}

const listTripApplications = `-- name: ListTripApplications :many
SELECT id, trip_id, passenger_id, boarding_station, payment_type, currency, contact_info, approved, created_at FROM trip_applications
WHERE trip_id = $1
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type ListTripApplicationsParams struct {
	TripID int64 `json:"trip_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTripApplications(ctx context.Context, arg ListTripApplicationsParams) ([]TripApplication, error) {
	rows, err := q.db.Query(ctx, listTripApplications, arg.TripID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripApplication{}
	for rows.Next() {
		var i TripApplication
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.PassengerID,
			&i.BoardingStation,
			&i.PaymentType,
			&i.Currency,
			&i.ContactInfo,
			&i.Approved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
