// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.2
// source: rpc_resort.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country   int64                  `protobuf:"varint,3,opt,name=country,proto3" json:"country,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Resort) Reset() {
	*x = Resort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resort) ProtoMessage() {}

func (x *Resort) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resort.ProtoReflect.Descriptor instead.
func (*Resort) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{0}
}

func (x *Resort) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Resort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resort) GetCountry() int64 {
	if x != nil {
		return x.Country
	}
	return 0
}

func (x *Resort) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateResortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country int64  `protobuf:"varint,2,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *CreateResortRequest) Reset() {
	*x = CreateResortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResortRequest) ProtoMessage() {}

func (x *CreateResortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResortRequest.ProtoReflect.Descriptor instead.
func (*CreateResortRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResortRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateResortRequest) GetCountry() int64 {
	if x != nil {
		return x.Country
	}
	return 0
}

type CreateResortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resort *Resort `protobuf:"bytes,1,opt,name=resort,proto3" json:"resort,omitempty"`
}

func (x *CreateResortResponse) Reset() {
	*x = CreateResortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResortResponse) ProtoMessage() {}

func (x *CreateResortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResortResponse.ProtoReflect.Descriptor instead.
func (*CreateResortResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResortResponse) GetResort() *Resort {
	if x != nil {
		return x.Resort
	}
	return nil
}

type GetResortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetResortRequest) Reset() {
	*x = GetResortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResortRequest) ProtoMessage() {}

func (x *GetResortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResortRequest.ProtoReflect.Descriptor instead.
func (*GetResortRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{3}
}

func (x *GetResortRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetResortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resort *Resort `protobuf:"bytes,1,opt,name=resort,proto3" json:"resort,omitempty"`
}

func (x *GetResortResponse) Reset() {
	*x = GetResortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResortResponse) ProtoMessage() {}

func (x *GetResortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResortResponse.ProtoReflect.Descriptor instead.
func (*GetResortResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{4}
}

func (x *GetResortResponse) GetResort() *Resort {
	if x != nil {
		return x.Resort
	}
	return nil
}

type ListResortsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country *int64  `protobuf:"varint,1,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Name    *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Limit   int64   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset  int64   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListResortsRequest) Reset() {
	*x = ListResortsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResortsRequest) ProtoMessage() {}

func (x *ListResortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResortsRequest.ProtoReflect.Descriptor instead.
func (*ListResortsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{5}
}

func (x *ListResortsRequest) GetCountry() int64 {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return 0
}

func (x *ListResortsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListResortsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListResortsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListResortsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resort []*Resort `protobuf:"bytes,1,rep,name=resort,proto3" json:"resort,omitempty"`
	Limit  int32     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32     `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Total  int64     `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListResortsResponse) Reset() {
	*x = ListResortsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResortsResponse) ProtoMessage() {}

func (x *ListResortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResortsResponse.ProtoReflect.Descriptor instead.
func (*ListResortsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{6}
}

func (x *ListResortsResponse) GetResort() []*Resort {
	if x != nil {
		return x.Resort
	}
	return nil
}

func (x *ListResortsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListResortsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListResortsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateResortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name    *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Country *int64  `protobuf:"varint,3,opt,name=country,proto3,oneof" json:"country,omitempty"`
}

func (x *UpdateResortRequest) Reset() {
	*x = UpdateResortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResortRequest) ProtoMessage() {}

func (x *UpdateResortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResortRequest.ProtoReflect.Descriptor instead.
func (*UpdateResortRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResortRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateResortRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateResortRequest) GetCountry() int64 {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return 0
}

type UpdateResortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resort *Resort `protobuf:"bytes,1,opt,name=resort,proto3" json:"resort,omitempty"`
}

func (x *UpdateResortResponse) Reset() {
	*x = UpdateResortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResortResponse) ProtoMessage() {}

func (x *UpdateResortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResortResponse.ProtoReflect.Descriptor instead.
func (*UpdateResortResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateResortResponse) GetResort() *Resort {
	if x != nil {
		return x.Resort
	}
	return nil
}

type DeleteResortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteResortRequest) Reset() {
	*x = DeleteResortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResortRequest) ProtoMessage() {}

func (x *DeleteResortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResortRequest.ProtoReflect.Descriptor instead.
func (*DeleteResortRequest) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResortRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteResortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteResortResponse) Reset() {
	*x = DeleteResortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_resort_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResortResponse) ProtoMessage() {}

func (x *DeleteResortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_resort_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResortResponse.ProtoReflect.Descriptor instead.
func (*DeleteResortResponse) Descriptor() ([]byte, []int) {
	return file_rpc_resort_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpc_resort_proto protoreflect.FileDescriptor

var file_rpc_resort_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x6f,
	0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x43, 0x0a, 0x13, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x22, 0x3a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x22, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x37, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x72,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x8f, 0x01, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x88, 0x01, 0x01, 0x12,
	0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7d, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x72, 0x0a, 0x13, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x3a,
	0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x72, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x6a, 0x69, 0x61, 0x32, 0x30, 0x31, 0x38, 0x2f, 0x70,
	0x65, 0x61, 0x6b, 0x2d, 0x70, 0x61, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_resort_proto_rawDescOnce sync.Once
	file_rpc_resort_proto_rawDescData = file_rpc_resort_proto_rawDesc
)

func file_rpc_resort_proto_rawDescGZIP() []byte {
	file_rpc_resort_proto_rawDescOnce.Do(func() {
		file_rpc_resort_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_resort_proto_rawDescData)
	})
	return file_rpc_resort_proto_rawDescData
}

var file_rpc_resort_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_resort_proto_goTypes = []interface{}{
	(*Resort)(nil),                // 0: pb.Resort
	(*CreateResortRequest)(nil),   // 1: pb.CreateResortRequest
	(*CreateResortResponse)(nil),  // 2: pb.CreateResortResponse
	(*GetResortRequest)(nil),      // 3: pb.GetResortRequest
	(*GetResortResponse)(nil),     // 4: pb.GetResortResponse
	(*ListResortsRequest)(nil),    // 5: pb.ListResortsRequest
	(*ListResortsResponse)(nil),   // 6: pb.ListResortsResponse
	(*UpdateResortRequest)(nil),   // 7: pb.UpdateResortRequest
	(*UpdateResortResponse)(nil),  // 8: pb.UpdateResortResponse
	(*DeleteResortRequest)(nil),   // 9: pb.DeleteResortRequest
	(*DeleteResortResponse)(nil),  // 10: pb.DeleteResortResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_rpc_resort_proto_depIdxs = []int32{
	11, // 0: pb.Resort.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: pb.CreateResortResponse.resort:type_name -> pb.Resort
	0,  // 2: pb.GetResortResponse.resort:type_name -> pb.Resort
	0,  // 3: pb.ListResortsResponse.resort:type_name -> pb.Resort
	0,  // 4: pb.UpdateResortResponse.resort:type_name -> pb.Resort
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rpc_resort_proto_init() }
func file_rpc_resort_proto_init() {
	if File_rpc_resort_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_resort_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResortsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResortsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_resort_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpc_resort_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_rpc_resort_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_resort_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_resort_proto_goTypes,
		DependencyIndexes: file_rpc_resort_proto_depIdxs,
		MessageInfos:      file_rpc_resort_proto_msgTypes,
	}.Build()
	File_rpc_resort_proto = out.File
	file_rpc_resort_proto_rawDesc = nil
	file_rpc_resort_proto_goTypes = nil
	file_rpc_resort_proto_depIdxs = nil
}
