// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.2
// source: rpc_create_carpool.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCarpoolRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContactInfo       string                 `protobuf:"bytes,1,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	DriverId          int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	MaxPassenger      uint64                 `protobuf:"varint,3,opt,name=max_passenger,json=maxPassenger,proto3" json:"max_passenger,omitempty"`
	Price             uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	AblePickUp        bool                   `protobuf:"varint,5,opt,name=able_pick_up,json=ablePickUp,proto3" json:"able_pick_up,omitempty"`
	ResortId          uint64                 `protobuf:"varint,6,opt,name=resort_id,json=resortId,proto3" json:"resort_id,omitempty"`
	AcceptPaymentType string                 `protobuf:"bytes,9,opt,name=accept_payment_type,json=acceptPaymentType,proto3" json:"accept_payment_type,omitempty"`
	Currency          string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	DepartureAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=departure_at,json=departureAt,proto3" json:"departure_at,omitempty"`
}

func (x *CreateCarpoolRequest) Reset() {
	*x = CreateCarpoolRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_carpool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCarpoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCarpoolRequest) ProtoMessage() {}

func (x *CreateCarpoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_carpool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCarpoolRequest.ProtoReflect.Descriptor instead.
func (*CreateCarpoolRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_carpool_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCarpoolRequest) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *CreateCarpoolRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *CreateCarpoolRequest) GetMaxPassenger() uint64 {
	if x != nil {
		return x.MaxPassenger
	}
	return 0
}

func (x *CreateCarpoolRequest) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateCarpoolRequest) GetAblePickUp() bool {
	if x != nil {
		return x.AblePickUp
	}
	return false
}

func (x *CreateCarpoolRequest) GetResortId() uint64 {
	if x != nil {
		return x.ResortId
	}
	return 0
}

func (x *CreateCarpoolRequest) GetAcceptPaymentType() string {
	if x != nil {
		return x.AcceptPaymentType
	}
	return ""
}

func (x *CreateCarpoolRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateCarpoolRequest) GetDepartureAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureAt
	}
	return nil
}

type CreateCarpoolResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Carpool *Carpool `protobuf:"bytes,1,opt,name=carpool,proto3" json:"carpool,omitempty"`
}

func (x *CreateCarpoolResponse) Reset() {
	*x = CreateCarpoolResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_carpool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCarpoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCarpoolResponse) ProtoMessage() {}

func (x *CreateCarpoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_carpool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCarpoolResponse.ProtoReflect.Descriptor instead.
func (*CreateCarpoolResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_carpool_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCarpoolResponse) GetCarpool() *Carpool {
	if x != nil {
		return x.Carpool
	}
	return nil
}

var File_rpc_create_carpool_proto protoreflect.FileDescriptor

var file_rpc_create_carpool_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x61, 0x72,
	0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0d, 0x63, 0x61, 0x72, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb,
	0x02, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x70, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x70,
	0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x6d, 0x61, 0x78, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x69, 0x63, 0x6b, 0x5f,
	0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x69,
	0x63, 0x6b, 0x55, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x49,
	0x64, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x3d, 0x0a,
	0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0b, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x41, 0x74, 0x22, 0x3e, 0x0a, 0x15,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x70, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x70, 0x6f, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x72, 0x70,
	0x6f, 0x6f, 0x6c, 0x52, 0x07, 0x63, 0x61, 0x72, 0x70, 0x6f, 0x6f, 0x6c, 0x42, 0x2c, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x63, 0x6b, 0x79,
	0x6a, 0x69, 0x61, 0x32, 0x30, 0x31, 0x38, 0x2f, 0x70, 0x65, 0x61, 0x6b, 0x70, 0x61, 0x6c, 0x2d,
	0x63, 0x61, 0x72, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rpc_create_carpool_proto_rawDescOnce sync.Once
	file_rpc_create_carpool_proto_rawDescData = file_rpc_create_carpool_proto_rawDesc
)

func file_rpc_create_carpool_proto_rawDescGZIP() []byte {
	file_rpc_create_carpool_proto_rawDescOnce.Do(func() {
		file_rpc_create_carpool_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_carpool_proto_rawDescData)
	})
	return file_rpc_create_carpool_proto_rawDescData
}

var file_rpc_create_carpool_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_carpool_proto_goTypes = []interface{}{
	(*CreateCarpoolRequest)(nil),  // 0: pb.CreateCarpoolRequest
	(*CreateCarpoolResponse)(nil), // 1: pb.CreateCarpoolResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*Carpool)(nil),               // 3: pb.Carpool
}
var file_rpc_create_carpool_proto_depIdxs = []int32{
	2, // 0: pb.CreateCarpoolRequest.departure_at:type_name -> google.protobuf.Timestamp
	3, // 1: pb.CreateCarpoolResponse.carpool:type_name -> pb.Carpool
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_create_carpool_proto_init() }
func file_rpc_create_carpool_proto_init() {
	if File_rpc_create_carpool_proto != nil {
		return
	}
	file_carpool_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_carpool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCarpoolRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_carpool_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCarpoolResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_carpool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_carpool_proto_goTypes,
		DependencyIndexes: file_rpc_create_carpool_proto_depIdxs,
		MessageInfos:      file_rpc_create_carpool_proto_msgTypes,
	}.Build()
	File_rpc_create_carpool_proto = out.File
	file_rpc_create_carpool_proto_rawDesc = nil
	file_rpc_create_carpool_proto_goTypes = nil
	file_rpc_create_carpool_proto_depIdxs = nil
}
