// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.2
// source: rpc_trip_application.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripApplication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID              int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TripId          int64                  `protobuf:"varint,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	PassengerId     int64                  `protobuf:"varint,3,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	BoardingStation int64                  `protobuf:"varint,4,opt,name=boarding_station,json=boardingStation,proto3" json:"boarding_station,omitempty"`
	PaymentType     string                 `protobuf:"bytes,5,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	ContactInfo     string                 `protobuf:"bytes,7,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	Approved        bool                   `protobuf:"varint,8,opt,name=approved,proto3" json:"approved,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *TripApplication) Reset() {
	*x = TripApplication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_trip_application_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripApplication) ProtoMessage() {}

func (x *TripApplication) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_trip_application_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripApplication.ProtoReflect.Descriptor instead.
func (*TripApplication) Descriptor() ([]byte, []int) {
	return file_rpc_trip_application_proto_rawDescGZIP(), []int{0}
}

func (x *TripApplication) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TripApplication) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *TripApplication) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *TripApplication) GetBoardingStation() int64 {
	if x != nil {
		return x.BoardingStation
	}
	return 0
}

func (x *TripApplication) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *TripApplication) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TripApplication) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *TripApplication) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *TripApplication) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTripApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TripId          int64  `protobuf:"varint,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	PassengerId     int64  `protobuf:"varint,3,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	BoardingStation int64  `protobuf:"varint,4,opt,name=boarding_station,json=boardingStation,proto3" json:"boarding_station,omitempty"`
	PaymentType     string `protobuf:"bytes,5,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Currency        string `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	ContactInfo     string `protobuf:"bytes,7,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
}

func (x *CreateTripApplicationRequest) Reset() {
	*x = CreateTripApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_trip_application_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTripApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripApplicationRequest) ProtoMessage() {}

func (x *CreateTripApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_trip_application_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateTripApplicationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_trip_application_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTripApplicationRequest) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *CreateTripApplicationRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *CreateTripApplicationRequest) GetBoardingStation() int64 {
	if x != nil {
		return x.BoardingStation
	}
	return 0
}

func (x *CreateTripApplicationRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreateTripApplicationRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateTripApplicationRequest) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

type CreateTripApplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TripApplication *TripApplication `protobuf:"bytes,1,opt,name=trip_application,json=tripApplication,proto3" json:"trip_application,omitempty"`
}

func (x *CreateTripApplicationResponse) Reset() {
	*x = CreateTripApplicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_trip_application_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTripApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripApplicationResponse) ProtoMessage() {}

func (x *CreateTripApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_trip_application_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateTripApplicationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_trip_application_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTripApplicationResponse) GetTripApplication() *TripApplication {
	if x != nil {
		return x.TripApplication
	}
	return nil
}

var File_rpc_trip_application_proto protoreflect.FileDescriptor

var file_rpc_trip_application_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc1, 0x02, 0x0a, 0x0f, 0x54, 0x72, 0x69, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x72, 0x69, 0x70, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x29, 0x0a, 0x10, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xe7, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x72, 0x69, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x72, 0x69, 0x70, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a,
	0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x5f, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x69, 0x70, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3e, 0x0a, 0x10, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x72, 0x69, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0f, 0x74, 0x72, 0x69, 0x70, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x69, 0x63, 0x6b, 0x79, 0x6a, 0x69, 0x61, 0x32, 0x30, 0x31, 0x38, 0x2f, 0x70, 0x65, 0x61, 0x6b,
	0x70, 0x61, 0x6c, 0x2d, 0x63, 0x61, 0x72, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_trip_application_proto_rawDescOnce sync.Once
	file_rpc_trip_application_proto_rawDescData = file_rpc_trip_application_proto_rawDesc
)

func file_rpc_trip_application_proto_rawDescGZIP() []byte {
	file_rpc_trip_application_proto_rawDescOnce.Do(func() {
		file_rpc_trip_application_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_trip_application_proto_rawDescData)
	})
	return file_rpc_trip_application_proto_rawDescData
}

var file_rpc_trip_application_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_trip_application_proto_goTypes = []interface{}{
	(*TripApplication)(nil),               // 0: pb.TripApplication
	(*CreateTripApplicationRequest)(nil),  // 1: pb.CreateTripApplicationRequest
	(*CreateTripApplicationResponse)(nil), // 2: pb.CreateTripApplicationResponse
	(*timestamppb.Timestamp)(nil),         // 3: google.protobuf.Timestamp
}
var file_rpc_trip_application_proto_depIdxs = []int32{
	3, // 0: pb.TripApplication.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: pb.CreateTripApplicationResponse.trip_application:type_name -> pb.TripApplication
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_trip_application_proto_init() }
func file_rpc_trip_application_proto_init() {
	if File_rpc_trip_application_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_trip_application_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripApplication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_trip_application_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTripApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_trip_application_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTripApplicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_trip_application_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_trip_application_proto_goTypes,
		DependencyIndexes: file_rpc_trip_application_proto_depIdxs,
		MessageInfos:      file_rpc_trip_application_proto_msgTypes,
	}.Build()
	File_rpc_trip_application_proto = out.File
	file_rpc_trip_application_proto_rawDesc = nil
	file_rpc_trip_application_proto_goTypes = nil
	file_rpc_trip_application_proto_depIdxs = nil
}
